version: '3'
services:

  db:
    container_name: rent-app-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: rent_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin

  app:
    container_name: rent-app
    image: rent-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      - "DB_DNS=db:3306"
    depends_on:
      - db