version: '3'
services:

  app:
    container_name: rent-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  db:
    container_name: rent-app-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
